inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Alias:
  EnforcedStyle: prefer_alias_method
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false
